const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=name=>JSON.parse(fs.readFileSync(path.join(root,'venue/concept',name)));
const manifest=read('manifest.json'),cad=read('cad-layout.json'),specs=read('model-specs.json'),sources=JSON.parse(fs.readFileSync(path.join(root,'venue/scenes.json'))),moduleReady=import('../venue/concept/manifest.mjs');
test('3D stops reference actual source photography and ordinary stills stay outside the renderer',async()=>{const{validateManifest}=await moduleReady;assert.equal(validateManifest(manifest,sources),manifest);assert.equal(manifest.kind,'ai-concept-3d');assert.ok(manifest.scenes.every(s=>s.panorama===undefined));assert.equal(sources.length,25);});
test('invalid camera stops, source IDs and hotspot links fail closed',async()=>{const{validateManifest}=await moduleReady;for(const change of[x=>x.scenes[0].sourceViewpointId='invented',x=>x.scenes[0].position=[NaN,0,0],x=>x.scenes[0].hall='C',x=>x.scenes[1].id=x.scenes[0].id,x=>x.hotspots[0].sceneId='missing',x=>x.stills[0].url='https://external.example/private.png']){const fixture=structuredClone(manifest);change(fixture);assert.throws(()=>validateManifest(fixture,sources));}});
test('all original table, chair, column and well counts remain intact',async()=>{const{validateCad}=await moduleReady;assert.equal(validateCad(cad),cad);assert.equal(cad.tables.filter(t=>t.hall==='A').length,256);assert.equal(cad.tables.filter(t=>t.hall==='B').length,192);assert.equal(cad.tables.flatMap(t=>t.source_chair_marks).length,896);assert.equal(cad.venue_grid.columns.length,8);assert.equal(cad.venue_grid.equipment_wells.length,48);assert.equal(cad.additional_original_linework.near_duplicate_table_outlines.length,1);});
test('four-table group and row identities retain original breaks',()=>{for(const hall of['A','B']){const groups=new Map();for(const t of cad.tables.filter(t=>t.hall===hall)){const id=t.row+'-'+t.group;groups.set(id,(groups.get(id)||0)+1);}assert.equal(groups.size,hall==='A'?64:48);assert.ok([...groups.values()].every(n=>n===4));}});
test('malformed source geometry or changed hall allocation fails closed',async()=>{const{validateCad}=await moduleReady;for(const change of[x=>x.tables.pop(),x=>x.tables[0].hall='B',x=>x.tables[0].source_chair_marks.pop(),x=>x.tables[0].venue_center_m[0]=NaN]){const fixture=structuredClone(cad);change(fixture);assert.throws(()=>validateCad(fixture));}});
test('confirmed concept footprint dimensions are separate from unverified heights and rigging',async()=>{const{validateSpecs}=await moduleReady;assert.equal(validateSpecs(specs),specs);assert.equal(specs.stage.illustrativeGeometryM.width,15.24);assert.equal(specs.stage.illustrativeGeometryM.depth,3.6576);assert.equal(specs['main-led'].illustrativeGeometryM.width,22.86);assert.equal(specs['main-led'].illustrativeGeometryM.height,6.096);assert.deepEqual(specs.stage.sourceDimensionsM,{});assert.equal(cad.proposed_stage_B.height_m,null);});
test('look controls wrap around a full circle, clamp vertical movement and bound zoom',async()=>{const{boundedPose}=await moduleReady;assert.deepEqual(boundedPose(370,100,20),{yaw:10,pitch:85,fov:35});assert.deepEqual(boundedPose(-370,-100,120),{yaw:-10,pitch:-85,fov:100});});
test('deep links resolve exact stops and handle malformed fragments',async()=>{const{sceneFromHash}=await moduleReady;assert.equal(sceneFromHash('#hall-a-coding',manifest.scenes).hall,'A');assert.equal(sceneFromHash('#%E0%A4%A',manifest.scenes),null);assert.equal(sceneFromHash('#missing',manifest.scenes),null);});
test('rendered CAD table matrices and chair-mark bounds preserve source coordinates',async()=>{
 const THREE=await import('../vendor/three/three.module.min.js'),{addCadLayout}=await import('../venue/concept/cad-model.js');
 for(const hall of['A','B']){const group=new THREE.Group(),result=addCadLayout(THREE,group,cad,hall,specs),original=cad.tables.filter(t=>t.hall===hall);assert.equal(result.tables.length,original.length);for(let i=0;i<original.length;i++){assert.deepEqual(result.tables[i].center,original[i].venue_center_m);assert.equal(result.tables[i].yaw,original[i].yaw_radians_in_venue_xy);}assert.deepEqual(result.chairMarks.map(m=>m.bounds),original.flatMap(t=>t.source_chair_marks.map(m=>m.venue_bounds_m)));
  const tops=group.children.filter(m=>m.isInstancedMesh&&m.geometry.parameters.width===1.8288&&m.geometry.parameters.depth===.9144),matrix=new THREE.Matrix4();assert.equal(tops.reduce((n,m)=>n+m.count,0),original.length);
  for(let color=0;color<tops.length;color++){const expected=original.filter(t=>Boolean(t.group%2)===(color===0));assert.equal(tops[color].count,expected.length);for(let i=0;i<expected.length;i++){tops[color].getMatrixAt(i,matrix);assert.ok(Math.abs(matrix.elements[12]-expected[i].venue_center_m[0])<.00001);assert.ok(Math.abs(matrix.elements[14]-expected[i].venue_center_m[1])<.00001);}}
  group.traverse(node=>{node.geometry?.dispose();node.material?.dispose();});
 }
});
test('nine source-mapped previews retain their reviewed image bytes and ordinary image format',()=>{
 const crypto=require('node:crypto'),stills=read('stills-manifest.json');assert.equal(manifest.stills.length,9);assert.equal(stills.length,9);
 for(const still of stills){const bytes=fs.readFileSync(path.join(root,'venue/concept',still.url));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),still.sha256);assert.equal(bytes.readUInt32BE(16),still.width);assert.equal(bytes.readUInt32BE(20),still.height);assert.equal(still.panorama,false);}
 assert.equal(new Set(manifest.scenes.map(s=>s.model)).size,8);assert.equal(manifest.scenes.length,11);
});
test('only one allocation study contains exactly seven full-scale sofas of each requested model',async()=>{
 const THREE=await import('../vendor/three/three.module.min.js'),{buildConceptSpace}=await import('../venue/concept/spaces.js');
 const prior=global.document;global.document={createElement:()=>({getContext:()=>({fillRect(){},fillText(){}})})};
 try{for(const key of new Set(manifest.scenes.filter(s=>s.model!=='exhibition').map(s=>s.model))){const model=buildConceptSpace(THREE,specs,key),sofas=[];model.room.traverse(n=>{if(n.userData.catalogId?.startsWith('sofa-'))sofas.push(n);});assert.equal(sofas.length,key==='judges-vip'?14:0);assert.equal(model.statistics.sofas,sofas.length);for(const sofa of sofas)assert.deepEqual(sofa.scale.toArray(),[1,1,1]);if(key==='judges-vip'){assert.equal(model.statistics.sofaSA50,7);assert.equal(model.statistics.sofaSA21,7);assert.equal(model.statistics.roomFitVerified,false);}model.dispose();}}
 finally{global.document=prior;}
});
