/* Shared, read-only page tours. Shadow DOM isolates help from the site's legacy CSS. */
(() => {
  if (window.self !== window.top) return; // The parent walkthrough teaches its embedded viewer.
  const base = new URL('../', document.currentScript.src);
  const seenKey = 'atlas-tutorial-welcome-v1';
  const host = document.createElement('div');
  host.id = 'atlas-tutorial';
  host.style.cssText = 'position:fixed;inset:0;pointer-events:none;z-index:2147483000';
  const root = host.attachShadow({mode:'open'});
  root.innerHTML = `<style>
    :host{font-family:Arial,sans-serif;color:#172c4d;font-size:15px;line-height:1.5}
    *{box-sizing:border-box} [hidden]{display:none!important}
    button,a{font:inherit}button{cursor:pointer;border:1px solid #9baec7;border-radius:9px;background:white;color:#172c4d;padding:9px 13px;min-height:42px}button:hover{background:#eaf3ff}button:focus-visible,a:focus-visible{outline:3px solid #1763e8;outline-offset:3px}button:disabled{opacity:.45;cursor:default}
    #launch{position:fixed;right:18px;bottom:18px;pointer-events:auto;box-shadow:0 4px 20px #172c4d22;background:#fff}
    #panel{position:fixed;pointer-events:auto;width:360px;max-width:calc(100vw - 24px);max-height:calc(100dvh - 24px);overflow:auto;background:#fff;border:1px solid #a6bcd8;border-radius:16px;padding:20px;box-shadow:0 14px 55px #142c4d40;right:16px;bottom:72px}
    h2{font-size:20px;line-height:1.25;margin:7px 0 12px}p{margin:0 0 14px}#count{font-size:12px;color:#486382;letter-spacing:.08em;text-transform:uppercase}footer{display:flex;gap:8px;align-items:center;flex-wrap:wrap}#next{background:#235fd2;color:#fff;border-color:#235fd2;margin-left:auto}#skip{border:0;text-decoration:underline;padding-left:0}#ring{position:fixed;border:3px solid #1662e7;border-radius:9px;pointer-events:none;box-shadow:0 0 0 5px #d8eaffb3}#hint{font-size:13px;color:#365579;background:#edf5ff;padding:9px;border-radius:8px}#pages{border-top:1px solid #dce4f0;margin-top:16px;padding-top:10px}summary{cursor:pointer}#links{display:flex;flex-wrap:wrap;gap:8px;padding-top:10px}a{color:#194fae;padding:4px}#focus{margin-bottom:12px;width:100%}
    @media(max-width:600px){#panel{padding:15px}h2{font-size:18px}#launch{right:12px;bottom:12px}}
  </style><div id="ring" hidden></div><button id="launch" aria-expanded="false">? Tutorial</button><section id="panel" role="dialog" aria-modal="false" aria-labelledby="title" hidden><div id="count" role="status" aria-live="polite"></div><h2 id="title"></h2><p id="text"></p><p id="hint" hidden></p><button id="focus" hidden>Show me where ↓</button><footer><button id="skip">Skip tutorial</button><button id="back">Back</button><button id="next" aria-describedby="title text hint">Next →</button></footer><details id="pages"><summary>Tutorials for other pages</summary><nav id="links" aria-label="Tutorial pages"></nav></details></section>`;
  document.body.append(host);
  const $ = id => root.getElementById(id);
  const routes = [['Home','index.html'],['Planning workspace','workspace.html'],['Operations','atlas-reference.html#direction'],['Outcomes','atlas-reference.html#outcomes'],['Operations register','atlas-reference.html#notebook'],['People','atlas-reference.html#people'],['Website','atlas-reference.html#web'],['Transport','atlas-reference.html#transport'],['Actions','atlas-reference.html#open'],['Virtual walkthrough','virtual-walkthrough.html'],['Venue explorer','venue/index.html']];
  routes.forEach(([label,path])=>{const a=document.createElement('a');const url=new URL(path,base);url.searchParams.set('tutorial','1');a.href=url;a.textContent=label;$('links').append(a);});
  const step=(selector,title,text,hint='')=>({selector,title,text,hint});
  const save=()=>step('#save-now','Keep your changes',window.AtlasTeam?.active ? 'Edits autosave to the shared plan. Click Save now and check the status before leaving. A conflict requires attention; Download backup keeps a separate copy.' : 'You are editing a personal browser draft. Click Save now and check the status. Sign in to load the separate shared plan; Download backup keeps a separate copy.');
  const visible = selector => [...document.querySelectorAll(selector)].find(el=>el.getClientRects().length && getComputedStyle(el).visibility!=='hidden');
  // Resolve the current rendered screen, including workspace subpages and operation tabs.
  function context(){
    if(document.querySelector('#map-planning-dialog[open]'))return 'transport-plan';
    if(document.querySelector('#personDialog[open]'))return 'profile';
    if(location.pathname.endsWith('/venue/index.html'))return 'viewer';
    if(location.pathname.endsWith('virtual-walkthrough.html'))return 'walkthrough';
    const peopleMode=document.querySelector('[data-pmode][aria-pressed="true"]')?.dataset.pmode;
    if(document.body.dataset.section==='people' && peopleMode && peopleMode!=='directory')return 'people:'+peopleMode;
    if(document.body.dataset.section)return 'operations:'+document.body.dataset.section;
    if(visible('#review-content'))return 'review:'+(document.querySelector('[data-review-tab][aria-pressed="true"]')?.dataset.reviewTab||'progress');
    if(visible('#itemRows'))return 'items';
    if(visible('.workstream-purpose'))return 'workstream';
    if(visible('#workspace'))return 'workspace';
    if(visible('.readable-home'))return 'home';
    return 'area';
  }
  const descriptions={direction:'Operations overview brings together the event plan, readiness and items that need attention.',outcomes:'Outcomes describe what success means and the sequence needed to achieve it.',notebook:'Choose a workstream, then review its owner, outcome, measures and tasks.',web:'Website planning tracks content, responsibilities and readiness. Planning here does not publish the public website.',open:'Actions are outstanding questions and decisions. Review the context before recording an answer.',exec:'Review the execution plan and responsibilities.',story:'Read the event story and supporting plan.',baseline:'Review the operating baseline and assumptions.',mobilize:'Mobilization tracks the gates that must be ready for each workstream.',refs:'These references explain planning concepts and source material.'};
  function stepsFor(key){
    if(key==='transport-plan')return [step('.map-dialog-head','Transport planning details','This dialog holds the full transport and school plan. Scroll inside it to read the sections below.'),step('#map-planning','Read the plan','Review ownership, the operating baseline and school information. Expand the detailed sections as needed; wide tables scroll sideways.'),step('.map-dialog-head button','Return to the map','Click Close or press Escape to return to the transport map.')];
    if(key==='profile')return [step('.profile-heading','Person profile','Read this person’s roles, organization and current source information here.'),step('.profile-contact','Contact information','Use the available email, phone or LinkedIn links. Missing contact fields mean that information has not been recorded.'),step('.profile-close','Back to the directory','Click this close button or press Escape to return to the people list.')];
    if(key.startsWith('people:'))return [step('#atlas-menu-toggle','People planning views','Open People in the left navigation to switch between the directory, stakeholders, communication map and school network.'),step('#peopleView','Review the detail','Read the groups, statuses and planning records. Prospects are not confirmations. Wide tables scroll sideways.'),save()];
    if(key==='home')return [step('.album-intro','Welcome to Atlas','This is your starting point for the Atlas Agentic AI Hackathon 2027. Use Next to explore, Back to revisit, or Skip tutorial at any time.'),step('.album-stage','Browse and open an album','Swipe or scroll sideways through the albums, or use the arrow buttons and Left/Right keys. Click an album cover to open its page. The Open button below also opens the selected album.'),step('#atlas-menu-toggle','Find your destination','People opens the roster; Transport opens the map; Operations register opens its separate plans. On smaller screens, use Menu to reveal the destinations. These links take you directly to the information you need.'),step('[data-album="4"]','Visit the venue','Slide to the Venue album and click its cover, or select 05 and click Open Venue walkthrough.')];
    if(key==='workspace')return [step('.workspace-heading','Your planning workspace','Start here to see the state of your plan.'),step('.status-gauge','Read progress correctly','Status cards show task counts and recorded measures against their planning targets. Awaiting data means no verified count has been entered; it is not a zero.'),step('#atlas-menu-toggle','Explore planning views','Open the left menu, then Planning workspace, for progress, ownership, recruitment, dependencies, decisions and website readiness.'),step('#deck-search','Find information quickly','Type a name or keyword here. Use the area filter beside it to narrow the results.'),step('.deck-tabs','Switch the register','Choose workstreams, people, tasks or dates to change the records shown.'),step('.stream-title','Open a workstream','Click a workstream title to see its lists. Open a list to update task status, owners, dates and notes.'),step('.signal-stack','See what needs attention','Waiting items and upcoming milestones appear here. Click an item to open its details.'),save()];
    if(key==='workstream')return [step('.workstream-purpose','Understand this workstream','Read the objective, accountable owner and success measures before editing.'),step('#atlas-menu-toggle','Choose how to work','Use these modes to browse lists, organize them, check them or work through unfinished items.'),step('#listRows, .check-row, .sheet','Open a list or unfinished item','Click a list title to view its tasks. Map, Menu, Message, Metrics and Money are in the disclosure below.'),step('.readiness-panel summary','Check readiness','Expand this section to see which planning checks are complete. Readiness is separate from task completion.'),save()];
    if(key==='items')return [step('#itemRows','Work through this list','Each row is a task. Scroll down the list to see more tasks.'),step('.item-controls','Record real progress','Choose To do, Doing, Waiting or Done. Only mark Done when the work is finished.'),step('.item-more summary','Edit details','Click Details to edit the owner, due date, working notes or tags, and add a note or decision.'),step('[data-action="show-add-item"]','Add a task','Click Add item to enter a new item, or Cancel to discard the unsaved addition. The tutorial does not change your data.'),step('#review','Review the list','Use Checked only after reviewing the list. Add a note explaining the review.'),save()];
    if(key.startsWith('review:'))return [step('#atlas-menu-toggle','Planning workspace reviews','Switch between progress, ownership, recruitment, dependencies, decisions and website readiness here.'),step('#review-content','Review and update','Progress links open tasks. Ownership assigns responsibility. Recruitment keeps forecasts separate from confirmations. Dependencies record release conditions. Decisions and readiness need supporting evidence.'),step('#review-content details summary, #review-content input, #review-content a, #review-content button','Explore the records','Expand a record or use a field to inspect its detail. Scroll down for more records; wide tables can be scrolled sideways.'),save()];
    if(key==='operations:direction')return [step('#directionView h2','Operations overview','See readiness, urgent gaps and workstream health in one place.'),step('.ws-health-card','Inspect a workstream','Each card separates planning and mobilization readiness. Click a card to open the workstream and address its gaps.'),step('#atlas-menu-toggle','Check the source','Open Operations & delivery in the left navigation for Planning baseline and Source references.'),step('#atlas-menu-toggle','Move between sections','The left navigation opens outcomes, workstreams, people, website content, transport and actions.'),save()];
    if(key==='operations:notebook')return [step('#atlas-menu-toggle','Choose a workstream','Open Operations & delivery → Workstream plans in the left navigation and choose a workstream.'),step('#filterBtn','Find ownership gaps','Click Owner gaps only to focus on workstreams missing a named owner. Click again to return to all workstreams.'),step('#panel','Read and edit the plan','The selected workstream opens here. Scroll through ownership, outcome, success measures and tasks. Expand sections where needed.'),step('#outcome','Define the outcome','Write the outcome in your own words. Recommendations are suggestions; accept them only after reviewing them.'),step('#newTask','Add work to the plan','Describe a task here, then click Add task. Record progress only when the work has actually changed.'),save()];
    if(key==='operations:outcomes')return [step('#outcomesView h2','Connect work to outcomes','This page links the event outcomes to the work needed to achieve them.'),step('#outcomesView button','Open a linked workstream','Click a workstream name to inspect its plan, owners and tasks.'),step('#outcomesView','Read the sequence','Scroll down through the outcomes and sequence. Check what must happen first before moving dependent work forward.'),step('#atlas-menu-toggle','Continue exploring','Use Workstreams to edit a plan, or Operations overview to return to the readiness summary.')];
    if(key==='operations:web')return [step('#webView h2','Website readiness','This is the content planning register. Updating a status here does not deploy a website.'),step('#atlas-menu-toggle','Choose a content item','Open Content areas in the left navigation and choose Judges, Coaches, Rules or another item.'),step('#webPanel','Review the content','Read the selected item, record progress and check the owner and review status. Scroll within the page to reach the remaining fields.'),save()];
    if(key==='operations:open')return [step('#oiWho','Find your actions','Choose a person to see their assigned actions. Everyone shows the full action list.'),step('#oiSup','Include supporting work','Turn this on to include actions where a person is supporting, alongside those they are accountable for.'),step('#openView .chk','Mark completed actions','Read an action and tick it only when it is complete. Scroll down for the other people and actions.'),save()];
    if(key==='operations:transport')return [step('#atlasMap','Explore transport','Drag the map to move around. Use the plus and minus controls to zoom. Markers are planning locations, not confirmed routes.'),step('.map-controls summary','Open the explorer','Click Transport explorer to show or hide the filters. On phones, close it for more map space.'),step('#map-style','Choose the map style','Choose street, satellite or dark mode. Wait for the map to finish loading before switching again.'),step('#map-category','Choose a transport group','Filter general public pickup points, high schools, colleges or universities.'),step('#map-search','Find a pickup','Search by location or parish. Scroll inside the pickup list and click a location to show it on the map.'),step('.map-buttons','Reset your view','Show network fits all matching locations. Venue centres the map on the convention centre.'),step('#map-open-planning','Read the full transport plan','Click here for the spacious planning dialog. Scroll inside it to read the details. Close it with Close or Escape.')];
    if(key==='operations:people')return [step('.directory-tools','People directory','Find judges, coaches, speakers and other contacts. Roster entries and prospects do not imply confirmed attendance.'),step('#peopleSearch','Search for someone','Type a name, role, company or contact detail. Use the role filters to narrow the roster.'),step('#peopleGrid','Read a profile','Each card shows the person, roles, status and available contact details. Use the profile control to open more information; email and LinkedIn links open their destinations.'),step('#peoplePagination','See more people','Use these controls for the next page of results. Clear your search to return to the full roster.')];
    if(key==='walkthrough')return [step('.venue-heading','Explore the convention centre','This page takes you through the venue using historic 360° photographs.'),step('.venue-window','Choose every viewpoint','Choose a space or use Previous and Next in the photograph. Drag to look around. Switch to the scroll tour if you prefer.', 'Try choosing a space or dragging, then click Next.'),step('.venue-progress','Track your journey','This counter shows your current viewpoint and the total. Keep scrolling to visit all the spaces.'),step('#atlas-menu-toggle','Return to Atlas','Open the navigation and select Home to return to the homepage. The Tutorial button is always available to restart the guide.')];
    if(key==='viewer')return [step('#viewer','Look around','Drag the panorama to turn. Focus the viewer and use arrow keys to look around, or + and − to zoom.'),step('#scene','Choose a space','Select a named space to jump directly to its panorama.'),step('.buttons','Move between viewpoints','Previous and Next take you through the venue one viewpoint at a time.'),step('aside:not(#atlas-sidebar) details summary','Floor plans and videos','Expand this section for floor plans and links to venue videos. These are references for exploring the space.')];
    if(key.startsWith('operations:')){const view=key.split(':')[1],id=view==='transport'?'transportPageView':view+'View';return [step('#atlas-menu-toggle','Navigate operations',descriptions[view]||'Review the plan in this section. The tabs switch between different parts of event operations.'),step(view==='notebook'?'#regList':`#${id} h2, #${id} h3`,'Start with the overview',view==='notebook'?'Click a workstream in this list to load its plan beside it.':'Read the section headings and summaries. They explain what each measure or record represents.'),step(view==='notebook'?'#panel':`#${id}`,'Explore the detail','Scroll down to see the remaining records. Click section headings with disclosure arrows to expand them. Wide tables scroll sideways.'),save()];}
    return [step('#atlas-menu-toggle','Navigate your plan','Use the left navigation to return to the workspace or parent workstream.'),step('.sheet','Choose a record','Click a row title to open its detail. Use Tutorial again on the new screen for more help.'),save()];
  }
  let active=false,welcome=false,index=0,steps=[],key='',target=null,returnFocus=null,frame=0;
  function remember(){try{localStorage.setItem(seenKey,'1');}catch{ /* Help still works when browser storage is blocked. */ }}
  function close(){active=false;welcome=false;target=null;$('panel').hidden=true;$('ring').hidden=true;$('launch').setAttribute('aria-expanded','false');remember();(returnFocus?.isConnected?returnFocus:$('launch')).focus();}
  function start(){remember();welcome=false;active=true;key=context();steps=stepsFor(key);index=0;show();}
  // Scroll the target (including its own scroll container) without triggering a click or edit.
  function reveal(){if(!target)return;for(let p=target.parentElement;p;p=p.parentElement){if(p.tagName==='DETAILS')p.open=true;}target.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});requestAnimationFrame(position);}
  function show(){
    $('panel').hidden=false;$('launch').setAttribute('aria-expanded','true');
    const s=steps[index];$('count').textContent=`Step ${index+1} of ${steps.length}`;$('title').textContent=s.title;$('text').textContent=s.text;$('hint').textContent=s.hint||'You can use the highlighted control, or click Next to continue.';$('hint').hidden=false;
    $('back').hidden=false;$('back').disabled=index===0;$('next').textContent=index===steps.length-1?'Finish ✓':'Next →';$('skip').textContent='Skip tutorial';
    target=visible(s.selector)||document.querySelector(s.selector);$('focus').hidden=!target;
    reveal();position();$('next').focus({preventScroll:true});
  }
  // Keep the outline anchored during scrolling and place the coach card away from the target.
  function position(){
    frame=0;if($('panel').hidden)return;
    if(active){const candidate=visible(steps[index].selector);if(candidate)target=candidate;}
    const r=target?.isConnected?target.getBoundingClientRect():null;
    const inView=r&&r.width&&r.height&&r.bottom>0&&r.top<innerHeight;
    $('ring').hidden=!inView;
    if(inView)Object.assign($('ring').style,{left:Math.max(2,r.left-4)+'px',top:Math.max(2,r.top-4)+'px',width:Math.min(innerWidth-4,r.right+4)-Math.max(2,r.left-4)+'px',height:Math.min(innerHeight-2,r.bottom+4)-Math.max(2,r.top-4)+'px'});
    const p=$('panel'),h=p.offsetHeight,w=p.offsetWidth;
    p.style.right='auto';p.style.bottom='auto';
    let x=innerWidth-w-12,y=innerHeight-h-72;
    if(inView){if(r.left>w+32)x=12;else if(r.right+w+24<innerWidth)x=r.right+12;
      if(r.bottom+h+24<innerHeight)y=r.bottom+12;else if(r.top-h-12>8)y=r.top-h-12;else y=r.top<innerHeight/2?innerHeight-h-12:12;}
    p.style.left=Math.max(12,x)+'px';p.style.top=Math.max(12,Math.min(y,innerHeight-h-12))+'px';
  }
  function schedule(){if(!frame)frame=requestAnimationFrame(position);}
  $('launch').onclick=()=>{returnFocus=$('launch');start();};$('skip').onclick=close;$('focus').onclick=reveal;
  $('next').onclick=()=>{if(welcome){start();return;}if(index===steps.length-1){close();return;}index++;show();};$('back').onclick=()=>{if(index>0){index--;show();}};
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('panel').hidden){close();}});
  addEventListener('scroll',schedule,true);addEventListener('resize',schedule);
  // A user may follow a highlighted link. Restart with the destination screen's steps.
  // Native dialogs live above page overlays. Keep help usable when a profile or plan opens.
  function followDialog(){
    const dialog=document.querySelector('dialog[open]')||document.querySelector('#atlas-sidebar[aria-modal="true"]:not([hidden])');
    const destination=dialog||document.body;
    if(host.parentElement!==destination)destination.append(host);
  }
  document.addEventListener('close',followDialog,true);
  let pending;new MutationObserver(()=>{clearTimeout(pending);pending=setTimeout(()=>{followDialog();if(active&&context()!==key)start();else schedule();},120);}).observe(document.getElementById('app')||document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','data-section','open']});
  let seen=false;try{seen=localStorage.getItem(seenKey)==='1';}catch{}
  if(new URLSearchParams(location.search).get('tutorial')==='1')setTimeout(start,500);
  // Help starts on request so it does not cover records on a first visit.
})();
